/// <reference lib="webworker" />
import { precacheAndRoute, cleanupOutdatedCaches } from "workbox-precaching";

declare let self: ServiceWorkerGlobalScope;

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Cleanup old caches
cleanupOutdatedCaches();

// Listen for the "install" event
self.addEventListener("install", () => {
    self.skipWaiting();
});

// Listen for the "activate" event
self.addEventListener("activate", (event) => {
    event.waitUntil(self.clients.claim());
});

/**
 * Handle Push Notifications
 */
self.addEventListener("push", (event) => {
    const data = event.data?.json() ?? {};
    const title = data.title ?? "Nihong Jastip";
    const options: NotificationOptions = {
        body: data.body ?? "Ada pembaruan untuk Anda.",
        icon: "/pwa-192x192.png",
        badge: "/pwa-192x192.png",
        data: data.url, // Store URL to open on click
        ...data.options,
    };

    event.waitUntil(self.registration.showNotification(title, options));
});

/**
 * Handle Notification Clicks
 */
self.addEventListener("notificationclick", (event) => {
    event.notification.close();

    const urlToOpen = event.notification.data || "/";

    event.waitUntil(
        self.clients.matchAll({ type: "window", includeUncontrolled: true }).then((windowClients) => {
            // If a window is already open, focus it
            for (let i = 0; i < windowClients.length; i++) {
                const client = windowClients[i];
                if (client.url === urlToOpen && "focus" in client) {
                    return client.focus();
                }
            }
            // Otherwise, open a new window
            if (self.clients.openWindow) {
                return self.clients.openWindow(urlToOpen);
            }
        })
    );
});

/**
 * Firebase Messaging Setup (Background)
 */
import { initializeApp } from "firebase/app";
import { getMessaging, onBackgroundMessage } from "firebase/messaging/sw";

const firebaseConfig = {
    apiKey: "AIzaSyAKLT4Q8cSJQAMMlPdY1_kND763IV63JKg",
    authDomain: "nihong-4b93e.firebaseapp.com",
    projectId: "nihong-4b93e",
    storageBucket: "nihong-4b93e.firebasestorage.app",
    messagingSenderId: "52461842773",
    appId: "1:52461842773:web:7422a8e7083bfa5d0affdc"
};

const app = initializeApp(firebaseConfig);
const messaging = getMessaging(app);

onBackgroundMessage(messaging, (payload) => {
    const notificationTitle = payload.notification?.title || 'Nihong Jastip';
    const notificationOptions = {
        body: payload.notification?.body || 'Ada pesan baru.',
        icon: '/pwa-192x192.png',
        badge: '/pwa-192x192.png',
    };

    self.registration.showNotification(notificationTitle, notificationOptions);
});

/**
 * Handle messages from the main thread
 */
self.addEventListener("message", (event) => {
    if (event.data && event.data.type === "SHOW_NOTIFICATION") {
        const { title, options } = event.data.payload;
        self.registration.showNotification(title, options);
    }
});
