/// <reference lib="webworker" />
import { precacheAndRoute, cleanupOutdatedCaches } from "workbox-precaching";

declare let self: ServiceWorkerGlobalScope;

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Cleanup old caches
cleanupOutdatedCaches();

// Listen for the "install" event
self.addEventListener("install", () => {
    self.skipWaiting();
});

// Listen for the "activate" event
self.addEventListener("activate", (event) => {
    event.waitUntil(self.clients.claim());
});

/**
 * Handle Push Notifications
 */
self.addEventListener("push", (event) => {
    const data = event.data?.json() ?? {};
    const title = data.title ?? "Nihong Jastip";
    const options: NotificationOptions = {
        body: data.body ?? "Ada pembaruan untuk Anda.",
        icon: "/pwa-192x192.png",
        badge: "/pwa-192x192.png",
        data: data.url, // Store URL to open on click
        ...data.options,
    };

    event.waitUntil(self.registration.showNotification(title, options));
});

/**
 * Handle Notification Clicks
 */
self.addEventListener("notificationclick", (event) => {
    event.notification.close();

    const urlToOpen = event.notification.data || "/";

    event.waitUntil(
        self.clients.matchAll({ type: "window", includeUncontrolled: true }).then((windowClients) => {
            // If a window is already open, focus it
            for (let i = 0; i < windowClients.length; i++) {
                const client = windowClients[i];
                if (client.url === urlToOpen && "focus" in client) {
                    return client.focus();
                }
            }
            // Otherwise, open a new window
            if (self.clients.openWindow) {
                return self.clients.openWindow(urlToOpen);
            }
        })
    );
});

/**
 * Handle messages from the main thread
 */
self.addEventListener("message", (event) => {
    if (event.data && event.data.type === "SHOW_NOTIFICATION") {
        const { title, options } = event.data.payload;
        self.registration.showNotification(title, options);
    }
});
